import type { VocabWord } from "@/types";

export const VOCAB_WORDS: VocabWord[] = [
  { id: "v01", word: "analyze", partOfSpeech: "verb", definition: "Examine something in detail to understand it better", example: "The researcher analyzed the data from 500 participants." },
  { id: "v02", word: "approach", partOfSpeech: "noun/verb", definition: "A way of dealing with a situation; to come near", example: "The professor's approach to teaching emphasizes critical thinking." },
  { id: "v03", word: "assess", partOfSpeech: "verb", definition: "Evaluate or estimate the quality or value of something", example: "Teachers assess students through both written tests and oral presentations." },
  { id: "v04", word: "assume", partOfSpeech: "verb", definition: "Accept something as true without proof", example: "The study assumes that all participants were honest in their responses." },
  { id: "v05", word: "concept", partOfSpeech: "noun", definition: "An abstract idea or general notion", example: "The concept of supply and demand is central to economics." },
  { id: "v06", word: "consistent", partOfSpeech: "adjective", definition: "Acting or done the same way over time; compatible with", example: "The results were consistent across all three experiments." },
  { id: "v07", word: "context", partOfSpeech: "noun", definition: "The circumstances surrounding an event that help explain it", example: "You need to understand the historical context to appreciate the painting." },
  { id: "v08", word: "contrast", partOfSpeech: "verb/noun", definition: "Compare to show differences; a difference between things", example: "The lecture contrasts traditional and modern approaches to medicine." },
  { id: "v09", word: "contribute", partOfSpeech: "verb", definition: "Give something to help achieve a result", example: "Regular exercise contributes significantly to mental health." },
  { id: "v10", word: "derive", partOfSpeech: "verb", definition: "Obtain something from a source", example: "Scientists derive many medicines from plants found in tropical rainforests." },
  { id: "v11", word: "distinct", partOfSpeech: "adjective", definition: "Recognizably different or separate", example: "The two species are distinct in both appearance and behavior." },
  { id: "v12", word: "dominate", partOfSpeech: "verb", definition: "Have a commanding influence over; be the most important factor", example: "Technology companies now dominate the global economy." },
  { id: "v13", word: "emerge", partOfSpeech: "verb", definition: "Come into being or become known", example: "New social norms emerged after the industrial revolution." },
  { id: "v14", word: "emphasize", partOfSpeech: "verb", definition: "Give special importance or attention to something", example: "The professor emphasized the importance of citing primary sources." },
  { id: "v15", word: "enable", partOfSpeech: "verb", definition: "Make something possible or allow someone to do something", example: "The internet has enabled people to work from anywhere in the world." },
  { id: "v16", word: "establish", partOfSpeech: "verb", definition: "Set up or prove something firmly", example: "The study established a clear link between diet and cognitive function." },
  { id: "v17", word: "evaluate", partOfSpeech: "verb", definition: "Form an opinion about something after careful thought", example: "Students must evaluate multiple sources before drawing conclusions." },
  { id: "v18", word: "evidence", partOfSpeech: "noun", definition: "Facts or information indicating whether something is true", example: "The lecture provided evidence that contradicted the reading passage." },
  { id: "v19", word: "factor", partOfSpeech: "noun", definition: "An element that contributes to a result", example: "Nutrition is one of the most important factors in academic performance." },
  { id: "v20", word: "function", partOfSpeech: "noun/verb", definition: "The purpose of something; to work or operate", example: "The function of the hippocampus is to consolidate long-term memories." },
  { id: "v21", word: "generate", partOfSpeech: "verb", definition: "Produce or create something", example: "Renewable energy sources generate electricity without pollution." },
  { id: "v22", word: "hypothesis", partOfSpeech: "noun", definition: "A proposed explanation made on limited evidence as a starting point", example: "The researcher's hypothesis was supported by the experimental results." },
  { id: "v23", word: "identify", partOfSpeech: "verb", definition: "Recognize and name something correctly", example: "The study identified three main causes of urban poverty." },
  { id: "v24", word: "impact", partOfSpeech: "noun/verb", definition: "A strong effect or influence; to have an effect on", example: "Climate change has a significant impact on biodiversity." },
  { id: "v25", word: "imply", partOfSpeech: "verb", definition: "Suggest something without directly stating it", example: "The professor's remarks implied that the textbook's conclusion was flawed." },
  { id: "v26", word: "indicate", partOfSpeech: "verb", definition: "Point out or show something", example: "Rising sea levels indicate that global warming is accelerating." },
  { id: "v27", word: "interpret", partOfSpeech: "verb", definition: "Explain the meaning of something", example: "Different historians interpret the same events in very different ways." },
  { id: "v28", word: "involve", partOfSpeech: "verb", definition: "Include as a necessary part or result", example: "The research involved interviewing over 200 students." },
  { id: "v29", word: "issue", partOfSpeech: "noun", definition: "An important topic or problem for debate", example: "Environmental protection is a critical issue facing modern societies." },
  { id: "v30", word: "maintain", partOfSpeech: "verb", definition: "Keep something at the same level; continue to state", example: "The scientist maintained that her original findings were correct." },
  { id: "v31", word: "major", partOfSpeech: "adjective", definition: "More important, serious, or significant", example: "Air pollution is a major public health concern in many cities." },
  { id: "v32", word: "method", partOfSpeech: "noun", definition: "A particular procedure for accomplishing something", example: "The Socratic method encourages learning through questions." },
  { id: "v33", word: "occur", partOfSpeech: "verb", definition: "Happen or take place", example: "Most learning occurs when students actively engage with material." },
  { id: "v34", word: "period", partOfSpeech: "noun", definition: "A length of time; a historical era", example: "The Renaissance was a period of remarkable artistic achievement." },
  { id: "v35", word: "policy", partOfSpeech: "noun", definition: "A set of rules adopted by an organization or government", example: "The university's new policy requires all students to take a writing course." },
  { id: "v36", word: "principle", partOfSpeech: "noun", definition: "A fundamental rule or belief guiding behavior", example: "The principle of cause and effect underlies all scientific research." },
  { id: "v37", word: "process", partOfSpeech: "noun/verb", definition: "A series of actions to achieve an end; to deal with something", example: "The digestive process converts food into energy the body can use." },
  { id: "v38", word: "propose", partOfSpeech: "verb", definition: "Put forward an idea or plan for consideration", example: "The reading passage proposes that remote work increases productivity." },
  { id: "v39", word: "provide", partOfSpeech: "verb", definition: "Make something available; supply", example: "The government should provide funding for public education." },
  { id: "v40", word: "require", partOfSpeech: "verb", definition: "Need something as a condition or necessity", example: "The TOEFL requires test-takers to demonstrate English proficiency." },
  { id: "v41", word: "research", partOfSpeech: "noun/verb", definition: "Systematic investigation to discover facts; to study carefully", example: "Recent research suggests that sleep deprivation impairs memory formation." },
  { id: "v42", word: "respond", partOfSpeech: "verb", definition: "React to something; give an answer", example: "The professor responded to the student's argument with counter-evidence." },
  { id: "v43", word: "role", partOfSpeech: "noun", definition: "The function or position something has in a situation", example: "Technology plays a central role in modern language learning." },
  { id: "v44", word: "significant", partOfSpeech: "adjective", definition: "Important or having a noticeable effect", example: "There was a significant improvement in test scores after the intervention." },
  { id: "v45", word: "similar", partOfSpeech: "adjective", definition: "Having qualities in common; resembling", example: "The two theories are similar in many respects but differ in their conclusions." },
  { id: "v46", word: "source", partOfSpeech: "noun", definition: "A place or person from which something comes", example: "Academic papers must cite reliable sources to be credible." },
  { id: "v47", word: "structure", partOfSpeech: "noun/verb", definition: "The way parts are organized; to arrange in a systematic way", example: "A well-structured essay helps readers follow the argument clearly." },
  { id: "v48", word: "sufficient", partOfSpeech: "adjective", definition: "Enough; adequate for a particular purpose", example: "The study did not have sufficient evidence to support its conclusion." },
  { id: "v49", word: "theory", partOfSpeech: "noun", definition: "A set of ideas intended to explain something", example: "Darwin's theory of evolution changed how scientists understand life on Earth." },
  { id: "v50", word: "vary", partOfSpeech: "verb", definition: "Differ; change from one situation or person to another", example: "The optimal study time varies greatly from student to student." },
];

export const VOCAB_IDS = VOCAB_WORDS.map((w) => w.id);
